#!/usr/bin/env bash
# This script pings an IP address passed as an argument
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
for i in {1..5}
do
    ping -c 1 "$1"
done
