#!/usr/bin/env bash
#  This script configures an Ubuntu server with specifict requirments
sudo sed -i '/^127\.0\.0\.1\s\+localhost$/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
