#!/usr/bin/env bash
#  This script configures an Ubuntu server with specifict requirments
cp /etc/hosts /tmp/hosts.new

sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /tmp/hosts.new
sed -i '/facebook\.com/d' /tmp/hosts.new
echo "8.8.8.8 facebook.com" >> /tmp/hosts.new

cp /tmp/hosts.new /etc/hosts

rm /tmp/hosts.news